version: '3.8'

services:
  nestjs-app:
    build: 
      context: .
      dockerfile: ./apps/fix-error/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: typeorm
    ports:
      - "5432:5432"